version: "3"

services:
    redis:
        image: redis
        container_name: redis
        command: redis-server --requirepass ${REDIS_PWD}
        ports: 
            - "6379:6379"
        volumes:
            - redis-data:/data
        hostname: redis-local
        networks:
            - development-network
    
    api:
        build: 
            dockerfile: Dockerfile.local
            context: .
        image: macgyver1985/api-backend-to-investiment-report
        container_name: api-investiment-report
        environment: 
            REDIS_PWD: "${REDIS_PWD}"
        ports:
            - "8080:80"
        networks:
            - development-network
        depends_on:
            - "redis"

networks:
    development-network:
        driver: bridge

volumes:
    redis-data:
