version: "3.8"

services:
    redis:
        image: redis
        container_name: redis
        command: redis-server --requirepass *hWuJ@e>sv}LG)W6=^F]
        ports: 
            - "6379:6379"
        volumes:
            - redis-data:/data
        hostname: redis-local
        networks:
            - development-network
        restart: on-failure

    api:
        build: 
            dockerfile: Dockerfile.local
            context: .
        image: macgyver1985/api-backend-to-investment-report
        container_name: api-investment-report
        volumes:
            - D:/WORK_ME/api-backend-to-investment-report/logs:/wwwroot/logs
        hostname: apirest01
        ports:
            - "8080:80"
        networks:
            - development-network
        restart: on-failure
        depends_on:
            - "redis"

networks:
    development-network:
        driver: bridge

volumes:
    redis-data:
