version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test .\src\ -v n --results-directory:coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\coverage
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Copy Files
          command: copy ./src ./app/src
      - run:
          name: Execute Test Application
          command: |
            cd app
            dotnet.exe test ./src -v n --results-directory:coverage --collect:"Code Coverage"
      - store_test_results:
          path: ~/src/coverage
      - store_artifacts:
          path: ~/src/coverage
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
